[package]
name = "horde_survival"
version = "0.1.0"
authors = ["pengowen123 <pengowen816@gmail.com>"]

[dependencies]
cgmath = "0.12.0"
image = "0.10.3"
gfx = "0.12.1"
gfx_window_glutin = "0.12.0"
gfx_device_gl = "0.11.2"
glutin = "0.6.2"
rand = "0.3"
log = "0.3"
log-panics = "1.0.0"
time = "0.1.35"
collision = "0.9.0"
random_choice = "0.3.2"
shader_version = "0.2.1"

[dependencies.conrod]
version = "0.44.0"
default-features = false
features = ["glutin"]

[dependencies.image_utils]
path = "image_utils"

[dependencies.clippy]
version = "*"
optional = true

[features]
default = ["clippy"]
