[package]
name = "horde_survival"
version = "0.1.0"
authors = ["pengowen123 <pengowen816@gmail.com>"]

[dependencies]
cgmath = "0.11.0"
image = "0.10.3"
gfx = "0.12.1"
gfx_core = "0.4.0"
gfx_window_glutin = "0.12.0"
gfx_device_gl = "0.11.2"
glutin = "0.6.1"
user32-sys = "0.2.0"
winapi = "0.2.8"
rand = "0.3"
log = "0.3"
log-panics = "1.0.0"
time = "0.1.35"
