[package]
name = "horde_survival"
version = "0.1.0"
authors = ["pengowen123 <pengowen816@gmail.com>"]

[dependencies]
cgmath = "0.7"
gfx = "0.12.0"
gfx_window_glutin = "*"
gfx_device_gl = "*"
glutin = "*"
user32-sys = "*"
winapi = "*"
rand = "0.3"
log = "0.3"
simplelog = "*"
