[package]
name = "horde_survival"
version = "0.1.0"
authors = ["pengowen123 <pengowen816@gmail.com>"]

[dependencies]
piston = "*"
glutin = "*"
cgmath = "*"
gfx = "*"
gfx_app = "*"
gfx_window_glutin = "*"
user32-sys = "*"
winapi = "*"
rand = "*"
log = "*"
simplelog = "*"
