[package]
authors = ["Owen Sanchez <pengowen816@gmail.com>"]
name = "rendergraph"
version = "0.1.0"

[dependencies]
cgmath = "0.15.0"
gfx = "0.16.2"
gfx_window_glutin = "0.19.0"
glutin = "0.11.0"
shred = "0.5.0"
