[package]
authors = ["Owen Sanchez <pengowen816@gmail.com>"]
name = "rendergraph"
version = "0.1.0"

[dependencies.common]
path = "../../common"

[dev-dependencies]
gfx = "0.17.1"

[[example]]
name = "triangle"
crate-type = ["bin"]
