pub const RANGE_THRESHOLD: f64 = 0.75;
pub const RANGE_TOO_CLOSE_THRESHOLD: f64 = 0.15;
pub const PROJECTILE_LEARNING_RATE: f64 = 0.3;
pub const ERROR_RESET_THRESHOLD: usize = 3;
pub const ERROR_INCREASE_THRESHOLD: f64 = 2.5;
