[package]
authors = ["Owen Sanchez <pengowen816@gmail.com>"]
name = "physics"
version = "0.1.0"

[dependencies]
shred-derive = "0.5.0"

[dependencies.common]
path = "../common"

[dependencies.math]
path = "../math"
