[package]
authors = ["Owen Sanchez <pengowen816@gmail.com>"]
name = "window"
version = "0.1.0"

[dependencies]
bitflags = "1.0.1"
shred-derive = "0.5.0"
slog = "2.2.3"

[dependencies.common]
path = "../common"
