[package]
authors = ["pengowen123 <pengowen816@gmail.com>"]
name = "image_utils"
version = "0.1.0"

[dependencies]
image = "0.14.0"
quick-error = "1.2.0"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx"
